url: "https://wikipod.io"

#page title
page_title: Wikipod - Listen to Wikipedia #Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: https://apps.apple.com/us/app/wikipod/id1475968398 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Wikipod
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Listen to more than 6 million wikipedia articles with an AI based human-like voice.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
# your_name: Emil
# your_link: https://emilbaehr.com
# your_city: Copenhagen
# email_address: emil.baehr@gmail.com
# facebook_username:
# instagram_username: ebaehr
# twitter_username: ebaehr
# github_username: emilbaehr
# youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Launch promo - 50% OFF
    description: Both packages with a huge launch price discount.
    fontawesome_icon_name: shopping-bag

  - title: It's yours.
    description: Pay once. Listen as many times after, for free.
    fontawesome_icon_name: retweet

  - title: Bookmarks
    description: Save your favorites for later.
    fontawesome_icon_name: bookmark

  - title: Save the audio
    description: Save them to your files. Or send them to a friend.
    fontawesome_icon_name: save

  - title: Listen offline
    description: Once downloaded, no need for internet connection.
    fontawesome_icon_name: link

  - title: Nearby
    description: Listen to nearby wikipedia articles.
    fontawesome_icon_name: location-arrow

  - title: Easy sign-in
    description: Just your e-mail and that is it.
    fontawesome_icon_name: envelope

  - title: Support an indie developer
    description: This is a one man job!
    fontawesome_icon_name: user

  - title: We give back to Wikipedia
    description: Part of the profits go to Wikipedia!
    fontawesome_icon_name: heart

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: https://images.unsplash.com/photo-1589903308904-1010c2294adc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80 # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

ampdir: amp

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - marketing_assets

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

screenshots:
  - 1.jpeg
  - 2.jpeg
  - 3.jpeg
  - 4.jpeg
